/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exemplo.view;

import com.exemplo.conexao.ConnectionFactory;
import com.exemplo.exception.DAOException;
import com.exemplo.repositorio.MySQLDAOManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vickz
 */
public class ViewMenu extends javax.swing.JFrame {

    private ConnectionFactory cf;
    private MySQLDAOManager manager;

    public ViewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        btCadCliente = new javax.swing.JMenuItem();
        btCadPedidos = new javax.swing.JMenuItem();
        btSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastros");

        btCadCliente.setMnemonic('o');
        btCadCliente.setText("Clientes");
        btCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadClienteActionPerformed(evt);
            }
        });
        fileMenu.add(btCadCliente);

        btCadPedidos.setMnemonic('s');
        btCadPedidos.setText("Pedidos");
        btCadPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadPedidosActionPerformed(evt);
            }
        });
        fileMenu.add(btCadPedidos);

        btSair.setMnemonic('x');
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        fileMenu.add(btSair);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadClienteActionPerformed
        try {
            cf = new ConnectionFactory();
            manager = new MySQLDAOManager(cf);
            
            ViewClientes viewCli = new ViewClientes(manager);
            this.desktopPane.add(viewCli);
            viewCli.setVisible(true);
        } catch (DAOException ex) {
            Logger.getLogger(ViewMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCadClienteActionPerformed

    private void btCadPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadPedidosActionPerformed
        try {
            cf = new ConnectionFactory();
            manager = new MySQLDAOManager(cf);

            ViewPedidos vp = new ViewPedidos(manager);
            this.desktopPane.add(vp);
            vp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ViewMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DAOException ex) {
            Logger.getLogger(ViewMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCadPedidosActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btCadCliente;
    private javax.swing.JMenuItem btCadPedidos;
    private javax.swing.JMenuItem btSair;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
